absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/python-course'
markdown: kramdown
css:
  active: "active"
collections:
  days:
    output: true
  students:
    output: false
defaults:
  -
    scope:
      path: ""
      type: "days"
    values:
      layout: "section"
