absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/python-course'
markdown: kramdown
name: Introduction to Programming for Research with Python
aimsprompt: "yourusername:python-course-homework"
hwprompt: "$"
css:
  active: "active"
collections:
  topic:
    output: true
    permalink: topic/:name/
  note:
    output: true
    permalink: note/:name/
  students:
    output: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: section
current: "2015-2016"
exclude:
 - run.sh
 - run-at-aims.sh
 - Gemfile
 - README.md
