absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/python-course'
markdown: kramdown
name: Programming for Research with Python
css:
  active: "active"
collections:
  topic:
    output: true
    permalink: topic/:name/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "section"
exclude:
 - run.sh
 - Gemfile
 - README.md
