absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/python-course'
repourl: 'https://github.com/AIMS-Ghana/python-course/tree/gh-pages/_includes'
markdown: kramdown
css:
  active: "active"
collections:
  days:
    output: true
  students:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "days"
    values:
      layout: "section"
  -
    scope:
      path: ""
      type: "students"
    values:
      layout: "blurb"
      status: "past"
  -
    scope:
      path: "students/2014-2015"
      type: "students"
    values:
      status: current
exclude:
 - run.sh
 - Gemfile
 - README.md
