absoluteurl: http://AIMS-Ghana.github.io
baseurl: ''
markdown: kramdown
collections:
  days:
    output: true
  students:
    output: false
defaults:
  -
    scope:
      path: ""
      type: "days"
    values:
      layout: "section"
